services:
  app:
    build: .
    volumes:
      - .:/workspace
    command: sleep infinity

  ## use local (docker.host.internal) ollama 
  #ollama:
  #  image: ollama/ollama:latest
  #  volumes:
  #    - ollama_data:/root/.ollama
  #  ports:
  #    - "11434:11434"

volumes:
  ollama_data:
